### ISSUE TITLE
On Safari, ripple effect appears as square box

### ISSUE THREAD

**Issue by frankiefu** [Polymer/paper-fab#12]
jsbin: http://jsbin.com/sivagurekohu/1/edit

![screen shot 2014-10-06 at 2 29 58 pm](https://cloud.githubusercontent.com/assets/116360/4533888/14308d6e-4da0-11e4-8b9a-17383a503e84.png)

**Comment by zdarovka** [comment]
I am still having this issue with Polymer 0.5.4 on Chrome for Android or in emulation in Chrome for desktop.

**Comment by bhavikup** [comment]
I am having this issue for Polymer 0.5.6 on Android for the default browser.

Edit:
For anyone looking for a fix: http://stackoverflow.com/questions/28490634/polymer-paper-fab-display-square-mask-in-mobile
